name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
    - name: Install Docker Compose
      run: |
        DOCKER_COMPOSE_VERSION="1.29.2"  # You can set the version you need
        sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
    - name: Verify Docker Compose
      run: docker-compose --version
    - name: Build and run Docker Compose
      run: |
        docker-compose build
        docker-compose up -d
    - name: Check running containers
      run: docker-compose ps
    - name: View container logs
      run: docker-compose logs
    - name: Stop and remove containers
      run: docker-compose down
