name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Compose
      run: docker-compose --version
    - name: Build and run Docker Compose
      run: |
        docker-compose build
        docker-compose up -d
    - name: Check running containers
      run: docker-compose ps
    - name: View container logs
      run: docker-compose logs
