name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name
    - name: Run the Docker container
      run: |
        docker run -d --name my-running-container my-image-name
        docker ps  # Optional: To verify the container is running
